Diagram(
    OneOrMore(
        Sequence(
            Optional(
                Choice(0,
                       Terminal('-'),
                       Terminal('+')
                      ),
                'skip'),
            Choice(0,
                   NonTerminal('term'),
                   Sequence(
                       Terminal('"'),
                       OneOrMore(
                           NonTerminal('term')
                       ),
                       Terminal('"')
                   )
                  )
        )
    )
)
